### ISSUE TITLE
[Bug] Unable to run Qwen3-Coder-Next-FP8

### ISSUE THREAD

**Issue by lovedheart** [guqiong96/Lsglang#1]
### Checklist

- [ ] I searched related issues but found no solution.
- [ ] The bug persists in the latest version.
- [ ] Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
- [ ] If this is not a bug report but a general question, please start a discussion at https://github.com/sgl-project/sglang/discussions. Otherwise, it will be closed.
- [ ] Please use English. Otherwise, it will be closed.

### Describe the bug

cmd: NCCL_SOCKET_IFNAME=lo NCCL_IB_DISABLE=1 GLOO_SOCKET_IFNAME=lo NCCL_SOCKET_TIMEOUT=600000 LVLLM_MOE_NUMA_ENABLED=1 LK_THREAD_BINDING=CPU_CORE LK_THREADS=4 OMP_NUM_THREADS=4 LVLLM_ENABLE_NUMA_INTERLEAVE=1 LVLLM_MOE_QUANT_ON_GPU=1 LVLLM_MOE_USE_WEIGHT=INT4 python -m sglang.launch_server     --model "/media/lovedheart/8EC4693CC46927A3/Qwen3-Coder-Next-FP8"     --served-model-name "Qwen3-Coder-Next-FP8"     --host 0.0.0.0     --port 8070     --trust-remote-code     --tensor-parallel-size 1     --max-running-requests 1     --enable-p2p-check     --chunked-prefill-size 512     --max-total-tokens 32768     --mem-fraction-static 0.50     --tool-call-parser qwen3_coder     --attention-backend triton


error:
[2026-02-19 12:45:22] mp.set_executable revert to /home/lovedheart/miniconda3/envs/Lsglang/bin/python
[2026-02-19 12:45:22] DeepGemm is enabled but the scale_fmt of checkpoint is not ue8m0. This might cause accuracy degradation on Blackwell.
[2026-02-19 12:45:22] Using default HuggingFace chat template with detected content format: string
[2026-02-19 12:45:27] DeepGemm is enabled but the scale_fmt of checkpoint is not ue8m0. This might cause accuracy degradation on Blackwell.
[2026-02-19 12:45:27] DeepGemm is enabled but the scale_fmt of checkpoint is not ue8m0. This might cause accuracy degradation on Blackwell.
[2026-02-19 12:45:27] Init torch distributed begin.
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[2026-02-19 12:45:27] Init torch distributed ends. elapsed=0.34 s, mem usage=0.02 GB
Detected CPU with AVX512-VNNI support
Loading _lk_moe_C_avx512_vnni.so
Successfully loaded MOE, MOEConfig, MOE_FP8, MOE_FP8Config, MOE_WNA16, MOE_WNA16Config, MOE_WNA16Repack, and MOE_WNA16RepackConfig, MOE_Quant, and MOE_QuantConfig
[2026-02-19 12:45:28] Ignore import error when loading sglang.srt.models.glm_ocr: No module named 'transformers.models.glm_ocr'
[2026-02-19 12:45:28] Ignore import error when loading sglang.srt.models.glm_ocr_nextn: No module named 'transformers.models.glm_ocr'
[2026-02-19 12:45:28] Ignore import error when loading sglang.srt.models.glmasr: cannot import name 'GlmAsrConfig' from 'transformers' (/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/transformers/__init__.py)
[2026-02-19 12:45:29] Load weight begin. avail mem=15.15 GB
[2026-02-19 12:45:29] Detected fp8 checkpoint.
`torch_dtype` is deprecated! Use `dtype` instead!
[2026-02-19 12:45:29] using attn output gate!
Loading safetensors checkpoint shards:   0% Completed | 0/40 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   2% Completed | 1/40 [00:01<01:00,  1.55s/it]
Loading safetensors checkpoint shards:   5% Completed | 2/40 [00:03<01:00,  1.58s/it]
Loading safetensors checkpoint shards:   8% Completed | 3/40 [00:04<00:58,  1.59s/it]
Loading safetensors checkpoint shards:  10% Completed | 4/40 [00:06<00:57,  1.59s/it]
Loading safetensors checkpoint shards:  12% Completed | 5/40 [00:07<00:55,  1.59s/it]
Loading safetensors checkpoint shards:  15% Completed | 6/40 [00:09<00:53,  1.59s/it]
Loading safetensors checkpoint shards:  18% Completed | 7/40 [00:11<00:52,  1.59s/it]
Loading safetensors checkpoint shards:  20% Completed | 8/40 [00:12<00:50,  1.59s/it]
Loading safetensors checkpoint shards:  22% Completed | 9/40 [00:14<00:48,  1.58s/it]
Loading safetensors checkpoint shards:  25% Completed | 10/40 [00:15<00:47,  1.57s/it]
Loading safetensors checkpoint shards:  28% Completed | 11/40 [00:17<00:45,  1.57s/it]
Loading safetensors checkpoint shards:  30% Completed | 12/40 [00:18<00:43,  1.57s/it]
Loading safetensors checkpoint shards:  32% Completed | 13/40 [00:20<00:42,  1.57s/it]
Loading safetensors checkpoint shards:  35% Completed | 14/40 [00:22<00:40,  1.57s/it]
Loading safetensors checkpoint shards:  38% Completed | 15/40 [00:23<00:39,  1.56s/it]
Loading safetensors checkpoint shards:  40% Completed | 16/40 [00:25<00:37,  1.57s/it]
Loading safetensors checkpoint shards:  42% Completed | 17/40 [00:26<00:35,  1.57s/it]
Loading safetensors checkpoint shards:  45% Completed | 18/40 [00:28<00:34,  1.57s/it]
Loading safetensors checkpoint shards:  48% Completed | 19/40 [00:30<00:33,  1.62s/it]
Loading safetensors checkpoint shards:  50% Completed | 20/40 [00:31<00:30,  1.55s/it]
Loading safetensors checkpoint shards:  52% Completed | 21/40 [00:33<00:29,  1.56s/it]
Loading safetensors checkpoint shards:  55% Completed | 22/40 [00:34<00:28,  1.56s/it]
Loading safetensors checkpoint shards:  57% Completed | 23/40 [00:36<00:26,  1.58s/it]
Loading safetensors checkpoint shards:  60% Completed | 24/40 [00:37<00:25,  1.58s/it]
Loading safetensors checkpoint shards:  62% Completed | 25/40 [00:39<00:23,  1.58s/it]
Loading safetensors checkpoint shards:  65% Completed | 26/40 [00:41<00:22,  1.60s/it]
Loading safetensors checkpoint shards:  68% Completed | 27/40 [00:42<00:20,  1.60s/it]
Loading safetensors checkpoint shards:  70% Completed | 28/40 [00:44<00:19,  1.59s/it]
Loading safetensors checkpoint shards:  72% Completed | 29/40 [00:45<00:17,  1.62s/it]
Loading safetensors checkpoint shards:  75% Completed | 30/40 [00:47<00:17,  1.75s/it]
Loading safetensors checkpoint shards:  78% Completed | 31/40 [00:49<00:15,  1.73s/it]
Loading safetensors checkpoint shards:  80% Completed | 32/40 [00:51<00:13,  1.71s/it]
Loading safetensors checkpoint shards:  82% Completed | 33/40 [00:52<00:11,  1.69s/it]
Loading safetensors checkpoint shards:  85% Completed | 34/40 [00:54<00:10,  1.67s/it]
Loading safetensors checkpoint shards:  88% Completed | 35/40 [00:56<00:08,  1.66s/it]
Loading safetensors checkpoint shards:  90% Completed | 36/40 [00:57<00:06,  1.65s/it]
Loading safetensors checkpoint shards:  92% Completed | 37/40 [00:59<00:04,  1.65s/it]
Loading safetensors checkpoint shards:  95% Completed | 38/40 [01:01<00:03,  1.63s/it]
Loading safetensors checkpoint shards:  98% Completed | 39/40 [01:02<00:01,  1.63s/it]
Loading safetensors checkpoint shards: 100% Completed | 40/40 [01:04<00:00,  1.63s/it]
Loading safetensors checkpoint shards: 100% Completed | 40/40 [01:04<00:00,  1.61s/it]

Read online CPUs: 16
Using LK_THREADS from environment: 4
Using thread binding to CPU cores
Process 0/1 using 4 threads (total across all processes: 4/16 CPUs)
GPU 0 PCI ID: 0000:01:00.0
Failed to get numa node for gpu_id: 0 pci_bus_id: 0000:01:00.0
Cannot use exclusive, falling back to INTERLEAVED
curr_process_numa_.start_node: 0, curr_process_numa_.end_node: 1
Backend_NUMA[0] init, thread_id: 0 cpu_id:0 core_id:0[0] node_id:0
Backend_NUMA[0] init, thread_id: 1 cpu_id:1 core_id:1[0] node_id:0
Backend_NUMA[0] init, thread_id: 2 cpu_id:2 core_id:2[0] node_id:0
Backend_NUMA[0] init, thread_id: 3 cpu_id:3 core_id:3[0] node_id:0
Backend_NUMA init suscess, numa nodes: 1 cors:8 cpus:16 max_threads: 4
[2026-02-19 12:46:39] Initialized lk_moe with 512 experts for layer 0 [CPU]
[2026-02-19 12:46:44] Initialized lk_moe with 512 experts for layer 1 [CPU]
[2026-02-19 12:46:50] Initialized lk_moe with 512 experts for layer 2 [CPU]
[2026-02-19 12:46:55] Initialized lk_moe with 512 experts for layer 3 [CPU]
[2026-02-19 12:47:00] Initialized lk_moe with 512 experts for layer 4 [CPU]
[2026-02-19 12:47:06] Initialized lk_moe with 512 experts for layer 5 [CPU]
[2026-02-19 12:47:11] Initialized lk_moe with 512 experts for layer 6 [CPU]
[2026-02-19 12:47:16] Initialized lk_moe with 512 experts for layer 7 [CPU]
[2026-02-19 12:47:22] Initialized lk_moe with 512 experts for layer 8 [CPU]
[2026-02-19 12:47:27] Initialized lk_moe with 512 experts for layer 9 [CPU]
[2026-02-19 12:47:32] Initialized lk_moe with 512 experts for layer 10 [CPU]
[2026-02-19 12:47:38] Initialized lk_moe with 512 experts for layer 11 [CPU]
[2026-02-19 12:47:43] Initialized lk_moe with 512 experts for layer 12 [CPU]
[2026-02-19 12:47:48] Initialized lk_moe with 512 experts for layer 13 [CPU]
[2026-02-19 12:47:54] Initialized lk_moe with 512 experts for layer 14 [CPU]
[2026-02-19 12:47:59] Initialized lk_moe with 512 experts for layer 15 [CPU]
[2026-02-19 12:48:04] Initialized lk_moe with 512 experts for layer 16 [CPU]
[2026-02-19 12:48:10] Initialized lk_moe with 512 experts for layer 17 [CPU]
[2026-02-19 12:48:15] Initialized lk_moe with 512 experts for layer 18 [CPU]
[2026-02-19 12:48:21] Initialized lk_moe with 512 experts for layer 19 [CPU]
[2026-02-19 12:48:26] Initialized lk_moe with 512 experts for layer 20 [CPU]
[2026-02-19 12:48:32] Initialized lk_moe with 512 experts for layer 21 [CPU]
[2026-02-19 12:48:37] Initialized lk_moe with 512 experts for layer 22 [CPU]
[2026-02-19 12:48:43] Initialized lk_moe with 512 experts for layer 23 [CPU]
[2026-02-19 12:48:48] Initialized lk_moe with 512 experts for layer 24 [CPU]
[2026-02-19 12:48:54] Initialized lk_moe with 512 experts for layer 25 [CPU]
[2026-02-19 12:49:00] Initialized lk_moe with 512 experts for layer 26 [CPU]
[2026-02-19 12:49:05] Initialized lk_moe with 512 experts for layer 27 [CPU]
[2026-02-19 12:49:11] Initialized lk_moe with 512 experts for layer 28 [CPU]
[2026-02-19 12:49:17] Initialized lk_moe with 512 experts for layer 29 [CPU]
[2026-02-19 12:49:22] Initialized lk_moe with 512 experts for layer 30 [CPU]
[2026-02-19 12:49:28] Initialized lk_moe with 512 experts for layer 31 [CPU]
[2026-02-19 12:49:33] Initialized lk_moe with 512 experts for layer 32 [CPU]
[2026-02-19 12:49:39] Initialized lk_moe with 512 experts for layer 33 [CPU]
[2026-02-19 12:49:44] Initialized lk_moe with 512 experts for layer 34 [CPU]
[2026-02-19 12:49:50] Initialized lk_moe with 512 experts for layer 35 [CPU]
[2026-02-19 12:49:55] Initialized lk_moe with 512 experts for layer 36 [CPU]
[2026-02-19 12:50:01] Initialized lk_moe with 512 experts for layer 37 [CPU]
[2026-02-19 12:50:06] Initialized lk_moe with 512 experts for layer 38 [CPU]
[2026-02-19 12:50:12] Initialized lk_moe with 512 experts for layer 39 [CPU]
[2026-02-19 12:50:18] Initialized lk_moe with 512 experts for layer 40 [CPU]
[2026-02-19 12:50:23] Initialized lk_moe with 512 experts for layer 41 [CPU]
[2026-02-19 12:50:29] Initialized lk_moe with 512 experts for layer 42 [CPU]
[2026-02-19 12:50:34] Initialized lk_moe with 512 experts for layer 43 [CPU]
[2026-02-19 12:50:40] Initialized lk_moe with 512 experts for layer 44 [CPU]
[2026-02-19 12:50:45] Initialized lk_moe with 512 experts for layer 45 [CPU]
[2026-02-19 12:50:51] Initialized lk_moe with 512 experts for layer 46 [CPU]
[2026-02-19 12:50:56] Initialized lk_moe with 512 experts for layer 47 [CPU]
[2026-02-19 12:50:58] Load weight end. elapsed=328.84 s, type=Qwen3NextForCausalLM, dtype=torch.bfloat16, avail mem=12.14 GB, mem usage=3.01 GB.
[2026-02-19 12:50:58] Using KV cache dtype: torch.bfloat16
[2026-02-19 12:50:58] Mamba Cache is allocated. max_mamba_cache_size: 29, conv_state size: 0.05GB, ssm_state size: 2.11GB 
[2026-02-19 12:50:58] KV Cache is allocated. #tokens: 32768, K size: 0.38 GB, V size: 0.38 GB
[2026-02-19 12:50:58] Memory pool end. avail mem=9.21 GB
[2026-02-19 12:50:59] Using hybrid linear attention backend for hybrid GDN models.
[2026-02-19 12:50:59] CuTe DSL GDN decode enabled: False
[2026-02-19 12:50:59] Capture cuda graph begin. This can take up to several minutes. avail mem=9.20 GB
[2026-02-19 12:50:59] Capture cuda graph bs [1]
Capturing batches (bs=1 avail_mem=9.20 GB):   0%|                                                                                                                                                                                       | 0/1 [00:00<?, ?it/s][2026-02-19 12:51:00] Entering DeepGEMM JIT Pre-Compile session. It may take a long time (typically 10-20 mins) if you have not run `sglang.compile_deep_gemm`. It is recommended to run `sglang.compile_deep_gemm` with same args as `sglang.launch_server` for pre-compilation to reduce the overhead if you have not run it before. For example: `python3 -m sglang.compile_deep_gemm --model deepseek-ai/DeepSeek-V3 --tp 8 --trust-remote-code`
[2026-02-19 12:51:00] Try DeepGEMM JIT Compiling for <GEMM_NT_F8F8BF16> N=12288, K=2048, num_groups=1 with all Ms. It only takes a little time (typically 1 sec) if you have run `python3 -m sglang.compile_deep_gemm`. 
[2026-02-19 12:51:00] Required memory for warmup: 0.4296875GB, Available memory: 9.2001953125GB
DeepGEMM warmup:   0%|                                                                                                                                                                                                              | 0/16384 [00:00<?, ?it/s]
Capturing batches (bs=1 avail_mem=9.20 GB):   0%|                                                                                                                                                                                       | 0/1 [00:01<?, ?it/s]
[2026-02-19 12:51:01] Scheduler hit an exception: Traceback (most recent call last):
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 370, in __init__
    self.capture()
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 526, in capture
    _capture_one_stream()
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 513, in _capture_one_stream
    ) = self.capture_one_batch_size(bs, forward, stream_idx)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 732, in capture_one_batch_size
    run_once()
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 719, in run_once
    logits_output_or_pp_proxy_tensors = forward(
                                        ^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/models/qwen3_next.py", line 975, in forward
    hidden_states = self.model(input_ids, positions, forward_batch, inputs_embeds)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/models/qwen3_next.py", line 876, in forward
    hidden_states, residual = layer(
                              ^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/models/qwen3_next.py", line 548, in forward
    hidden_states = self.linear_attn(
                    ^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/models/qwen3_next.py", line 410, in forward
    projected_states_qkvz, projected_states_ba = self._forward_input_proj(
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/models/qwen3_next.py", line 394, in _forward_input_proj
    projected_states_qkvz, _ = self.in_proj_qkvz(hidden_states)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/linear.py", line 451, in forward
    output_parallel = self.quant_method.apply(self, input_, bias)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/quantization/fp8.py", line 638, in apply
    return self.w8a8_block_fp8_linear(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/quantization/fp8_utils.py", line 480, in deepgemm_w8a8_block_fp8_linear_with_fallback
    output = w8a8_block_fp8_matmul_deepgemm(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/quantization/fp8_kernel.py", line 1085, in w8a8_block_fp8_matmul_deepgemm
    deep_gemm_fp8_fp8_bf16_nt(A, As, B, Bs, C)
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/_ops.py", line 1255, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/quantization/fp8_kernel.py", line 114, in deep_gemm_fp8_fp8_bf16_nt
    deep_gemm_wrapper.gemm_nt_f8f8bf16((A, As), (B, Bs), C)
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/deep_gemm_wrapper/entrypoint.py", line 97, in gemm_nt_f8f8bf16
    with compile_utils.deep_gemm_execution_hook(m, n, k, num_groups, kernel_type):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/deep_gemm_wrapper/compile_utils.py", line 325, in deep_gemm_execution_hook
    _maybe_compile_deep_gemm_one_type_all(kernel_type, n, k, num_groups)
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/deep_gemm_wrapper/compile_utils.py", line 140, in _maybe_compile_deep_gemm_one_type_all
    _compile_deep_gemm_one_type_all(
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/deep_gemm_wrapper/compile_utils.py", line 200, in _compile_deep_gemm_one_type_all
    executor.execute(m=m)
  File "/home/lovedheart/Lsglang/python/sglang/srt/layers/deep_gemm_wrapper/compile_utils.py", line 277, in execute
    deep_gemm.fp8_gemm_nt(
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/deep_gemm/__init__.py", line 50, in _fn
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/miniconda3/envs/Lsglang/lib/python3.12/site-packages/torch/_ops.py", line 1255, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Assertion error (_deps/repo-deepgemm-src/csrc/apis/../jit_kernels/impls/../heuristics/../../utils/layout.hpp:56): Unknown recipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lovedheart/Lsglang/python/sglang/srt/managers/scheduler.py", line 3121, in run_scheduler_process
    scheduler = Scheduler(
                ^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/managers/scheduler.py", line 360, in __init__
    self.init_model_worker()
  File "/home/lovedheart/Lsglang/python/sglang/srt/managers/scheduler.py", line 553, in init_model_worker
    self.init_tp_model_worker()
  File "/home/lovedheart/Lsglang/python/sglang/srt/managers/scheduler.py", line 511, in init_tp_model_worker
    self.tp_worker = TpModelWorker(
                     ^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/managers/tp_worker.py", line 247, in __init__
    self._init_model_runner()
  File "/home/lovedheart/Lsglang/python/sglang/srt/managers/tp_worker.py", line 330, in _init_model_runner
    self._model_runner = ModelRunner(
                         ^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 428, in __init__
    self.initialize(min_per_gpu_memory)
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 624, in initialize
    self.init_device_graphs()
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 2199, in init_device_graphs
    self.graph_runner = graph_runners[self.device](self)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovedheart/Lsglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 372, in __init__
    raise Exception(
Exception: Capture cuda graph failed: Assertion error (_deps/repo-deepgemm-src/csrc/apis/../jit_kernels/impls/../heuristics/../../utils/layout.hpp:56): Unknown recipe
Possible solutions:
1. set --mem-fraction-static to a smaller value (e.g., 0.8 or 0.7)
2. set --cuda-graph-max-bs to a smaller value (e.g., 16)
3. disable torch compile by not using --enable-torch-compile
4. disable CUDA graph by --disable-cuda-graph. (Not recommended. Huge performance loss)
Open an issue on GitHub https://github.com/sgl-project/sglang/issues/new/choose 


[2026-02-19 12:51:01] Received sigquit from a child process. It usually means the child failed.
Killed



### Reproduction

cmd: NCCL_SOCKET_IFNAME=lo NCCL_IB_DISABLE=1 GLOO_SOCKET_IFNAME=lo NCCL_SOCKET_TIMEOUT=600000 LVLLM_MOE_NUMA_ENABLED=1 LK_THREAD_BINDING=CPU_CORE LK_THREADS=4 OMP_NUM_THREADS=4 LVLLM_ENABLE_NUMA_INTERLEAVE=1 LVLLM_MOE_QUANT_ON_GPU=1 LVLLM_MOE_USE_WEIGHT=INT4 python -m sglang.launch_server     --model "/media/lovedheart/8EC4693CC46927A3/Qwen3-Coder-Next-FP8"     --served-model-name "Qwen3-Coder-Next-FP8"     --host 0.0.0.0     --port 8070     --trust-remote-code     --tensor-parallel-size 1     --max-running-requests 1     --enable-p2p-check     --chunked-prefill-size 512     --max-total-tokens 32768     --mem-fraction-static 0.50     --tool-call-parser qwen3_coder     --attention-backend triton

### Environment

(Lsglang) lovedheart@lovedheart-GEM12:~/Lsglang$ python3 -m sglang.check_env
Python: 3.12.11 | packaged by Anaconda, Inc. | (main, Jun  5 2025, 13:09:17) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 5060 Ti
GPU 0 Compute Capability: 12.0
CUDA_HOME: /usr/local/cuda-12.9
NVCC: Cuda compilation tools, release 12.9, V12.9.86
CUDA Driver Version: 580.126.16
PyTorch: 2.9.1+cu128
sglang: 0.5.8+lsglang.1.0.3
sgl_kernel: 0.3.21
flashinfer_python: 0.6.3
flashinfer_cubin: 0.6.3
flashinfer_jit_cache: Module Not Found
triton: 3.5.1
transformers: 4.57.1
torchao: 0.9.0
numpy: 2.4.1
aiohttp: 3.13.3
fastapi: 0.123.3
hf_transfer: 0.1.9
huggingface_hub: 0.36.2
interegular: 0.3.3
modelscope: 1.34.0
orjson: 3.11.5
outlines: 0.1.11
packaging: 25.0
psutil: 7.2.2
pydantic: 2.12.3
python-multipart: 0.0.21
pyzmq: 27.1.0
uvicorn: 0.38.0
uvloop: 0.22.1
vllm: Module Not Found
xgrammar: 0.1.27
openai: 2.6.1
tiktoken: 0.12.0
anthropic: 0.75.0
litellm: Module Not Found
decord2: 3.0.0
NVIDIA Topology: 
	GPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	0-15	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1024

**Comment by guqiong96** [comment]
SGLANG_ENABLE_JIT_DEEPGEMM=0 \
NCCL_SOCKET_IFNAME=lo \
NCCL_IB_DISABLE=1 \
GLOO_SOCKET_IFNAME=lo \
NCCL_SOCKET_TIMEOUT=600000 \
LVLLM_MOE_NUMA_ENABLED=1 \
LK_THREAD_BINDING=CPU_CORE \
LK_THREADS=4 \
OMP_NUM_THREADS=4 \
LVLLM_MOE_USE_WEIGHT=INT4 \
LVLLM_ENABLE_NUMA_INTERLEAVE=1 \
LVLLM_MOE_QUANT_ON_GPU=1 \
python -m sglang.launch_server \
--model /media/lovedheart/8EC4693CC46927A3/Qwen3-Coder-Next-FP8 \
--served-model-name Qwen3-Coder-Next-FP8 \
--host 0.0.0.0 \
--port 8070 \
--trust-remote-code \
--tensor-parallel-size 1 \
--max-running-requests 1 \
--enable-p2p-check \
--chunked-prefill-size 512 \
--max-total-tokens 32768 \
--mem-fraction-static 0.50 \
--tool-call-parser qwen3_coder \
--attention-backend triton \
--fp8-gemm-backend triton

**Comment by guqiong96** [comment]
I need to see the complete output information to know the backend of fp8 and other parameter information; the full output text is necessary to help solve the problem.

**Comment by lovedheart** [comment]
问题已解决
