### ISSUE TITLE
[Bug] glm5.1加入mtp会报错，命令参数行如下

### ISSUE THREAD

**Issue by zhangjiekui** [guqiong96/Lsglang#7]
### Checklist

- [x] I searched related issues but found no solution.
- [x] The bug persists in the latest version.
- [x] Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
- [ ] If this is not a bug report but a general question, please start a discussion at https://github.com/sgl-project/sglang/discussions. Otherwise, it will be closed.
- [ ] Please use English. Otherwise, it will be closed.

### Describe the bug

Multi-thread loading shards: 100% Completed | 142/142 [00:25<00:00,  5.66it/s]
[2026-04-16 01:02:09 TP1] Failed to initialize lk_moe: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 1 has a total capacity of 47.37 GiB of                              which 4.31 MiB is free. Including non-PyTorch memory, this process has 47.35 GiB memory in use. Of the allocated memory 45.63 GiB is allocated by P                             yTorch, with 24.00 MiB allocated in private pools (e.g., CUDA Graphs), and 1.10 GiB is reserved by PyTorch but unallocated. If reserved but unalloc                             ated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management                               (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2026-04-16 01:02:09 TP0] **Failed to initialize lk_moe: CUDA out of memory. Tried to allocate 24.00 MiB**. GPU 0 has a total capacity of 47.37 GiB of                              which 4.31 MiB is free. Including non-PyTorch memory, this process has 47.35 GiB memory in use. Of the allocated memory 45.63 GiB is allocated by P                             yTorch, with 24.00 MiB allocated in private pools (e.g., CUDA Graphs), and 1.10 GiB is reserved by PyTorch but unallocated. If reserved but unalloc                             ated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management                               (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2026-04-16 01:02:15 TP1] Load weight end. elapsed=31.83 s, type=DeepseekV3ForCausalLMNextN, quant=fp8, fmt=e4m3, avail mem=5.16 GB, mem usage=3.56                              GB.
[2026-04-16 01:02:15 TP0] Load weight end. elapsed=31.84 s, type=DeepseekV3ForCausalLMNextN, quant=fp8, fmt=e4m3, avail mem=5.16 GB, mem usage=3.56                              GB.
[2026-04-16 01:02:15 TP0] Using KV cache dtype: torch.bfloat16
[2026-04-16 01:02:15 TP0] KV Cache is allocated. #tokens: 230912, KV size: 0.28 GB
[2026-04-16 01:02:15 TP0] Memory pool end. avail mem=5.16 GB
[2026-04-16 01:02:15 TP1] KV Cache is allocated. #tokens: 230912, KV size: 0.28 GB
[2026-04-16 01:02:15 TP1] Memory pool end. avail mem=5.16 GB
[2026-04-16 01:02:15 TP0] Scheduler hit an exception: Traceback (most recent call last):
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/scheduler.py", line 3600, in run_scheduler_process
    scheduler = Scheduler(
                ^^^^^^^^^^
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/scheduler.py", line 385, in __init__
    self.init_model_worker()
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/scheduler.py", line 633, in init_model_worker
    self.maybe_init_draft_worker()
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/scheduler.py", line 629, in maybe_init_draft_worker
    self.draft_worker = DraftWorkerClass(**draft_worker_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cppsrc/Lsglang/python/sglang/srt/speculative/eagle_worker.py", line 142, in __init__
    super().__init__(
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/tp_worker.py", line 261, in __init__
    self._init_model_runner()
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/tp_worker.py", line 344, in _init_model_runner
    self._model_runner = ModelRunner(
                         ^^^^^^^^^^^^
  File "/data/cppsrc/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 444, in __init__
    self.initialize(pre_model_load_memory)
  File "/data/cppsrc/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 671, in initialize
    self.kernel_warmup()
  File "/data/cppsrc/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 2082, in kernel_warmup
    self._dummy_run(
  File "/data/cppsrc/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 2149, in _dummy_run
    raise RuntimeError("This should not happen")
RuntimeError: This should not happen

[2026-04-16 01:02:15] Received sigquit from a child process. It usually means the child failed.
[2026-04-16 01:02:15 TP1] Scheduler hit an exception: Traceback (most recent call last):
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/scheduler.py", line 3600, in run_scheduler_process
    scheduler = Scheduler(
                ^^^^^^^^^^
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/scheduler.py", line 385, in __init__
    self.init_model_worker()
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/scheduler.py", line 633, in init_model_worker
    self.maybe_init_draft_worker()
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/scheduler.py", line 629, in maybe_init_draft_worker
    ****self.draft_worker = DraftWorkerClass(**draft_worker_kwargs)****
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cppsrc/Lsglang/python/sglang/srt/speculative/eagle_worker.py", line 142, in __init__
    super().__init__(
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/tp_worker.py", line 261, in __init__
    self._init_model_runner()
  File "/data/cppsrc/Lsglang/python/sglang/srt/managers/tp_worker.py", line 344, in _init_model_runner
    self._model_runner = ModelRunner(
                         ^^^^^^^^^^^^
  File "/data/cppsrc/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 444, in __init__
    self.initialize(pre_model_load_memory)
  File "/data/cppsrc/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 671, in initialize
    self.kernel_warmup()
  File "/data/cppsrc/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 2082, in kernel_warmup
    self._dummy_run(
  File "/data/cppsrc/Lsglang/python/sglang/srt/model_executor/model_runner.py", line 2149, in _dummy_run
    raise RuntimeError("This should not happen")

### Reproduction

  --speculative-algorithm EAGLE \
  --speculative-num-steps 3 \
  --speculative-eagle-topk 1 \
  --speculative-num-draft-tokens 4 \

### Environment

2*48G 魔改版4090显卡
感觉是这个权重没有放到CPU
我试过ktransformers，是可以成功加载运行的

**Comment by guqiong96** [comment]
显存爆了，跟mtp无关

**Comment by guqiong96** [comment]
3090双卡可以运行的命令：sync && echo 3 | sudo tee /proc/sys/vm/drop_caches

PYTORCH_ALLOC_CONF=expandable_segments:True \
SGLANG_FORCE_FP8_MARLIN=1 \
SGLANG_ENABLE_JIT_DEEPGEMM=0 \
NCCL_SOCKET_IFNAME=lo \
NCCL_IB_DISABLE=1 \
GLOO_SOCKET_IFNAME=lo \
NCCL_SOCKET_TIMEOUT=600000 \
LVLLM_MOE_NUMA_ENABLED=1 \
LK_THREAD_BINDING=CPU_CORE \
LK_THREADS=44 \
OMP_NUM_THREADS=44 \
LVLLM_MOE_USE_WEIGHT=INT4 \
LVLLM_ENABLE_NUMA_INTERLEAVE=1 \
LVLLM_MOE_QUANT_ON_GPU=0 \
LVLLM_GPU_PREFETCH_WINDOW=1 \
LVLLM_GPU_PREFILL_MIN_BATCH_SIZE=2048 \
python -m sglang.launch_server \
    --model "/home/guqiong/Models/GLM-5.1-FP8" \
    --served-model-name "GLM-5.1-FP8" \
    --host "0.0.0.0" \
    --port "8070" \
    --trust-remote-code \
    --tensor-parallel-size 2 \
    --enable-p2p-check \
    --max-running-requests 2 \
    --tool-call-parser glm47 \
    --reasoning-parser glm45 \
    --chunked-prefill-size 16384 \
    --max-total-tokens 32768 \
    --mem-fraction-static 0.92 \
    --attention-backend triton \
    --fp8-gemm-backend triton \
    --kv-cache-dtype bf16 \
    --disable-piecewise-cuda-graph \
    --disable-shared-experts-fusion

**Comment by zhangjiekui** [comment]
谢谢回复，如果不加：
--speculative-algorithm EAGLE
--speculative-num-steps 3
--speculative-eagle-topk 1
--speculative-num-draft-tokens 4 
是可以正常运行的，但是加了，就会爆显存！

**Comment by guqiong96** [comment]
之前有个bug，会报错，我现在用这个在qwen3.6 35B a3b运行通过，是会加载草稿模型，增加显存占用，后面我再测下glm5.1 fp8，估计显存不够开：### 开启推测解码

开启推测解码后，草稿模型会增加显存占用，在实际应用环境输出速度可能会有提升，在完全随机测试页面速度会大幅下降，以下参数在Qwen3.6 35B A3B上测试通过，其它模型需要到模型下载页面查看参数设置
```bash
# 增加环境变量
SGLANG_ENABLE_SPEC_V2=1
# 增加命令参数
--speculative-algo NEXTN
--speculative-num-steps 3
--speculative-eagle-topk 1
--speculative-num-draft-tokens 4
--mamba-scheduler-strategy extra_buffer

**Comment by guqiong96** [comment]
新版lsglang-v1.4.1修复了这个bug，取消了LVLLM_MOE_USE_WEIGHT=INT4, 能跑nvfp4版本， 显存紧张，并且2080ti还不能开启gpu prefill

**Comment by guqiong96** [comment]
最新版支持mtp了
